version: "3.7"
services:

  # Snapshot hub
  snapshot-hub:
    build: .
    container_name: snapshot-hub
    env_file:
      - .env
    environment:
      RATE_LIMIT_DATABASE_URL: redis://redis:6379
      # HUB_DATABASE_URL: mysql://admin:pwd@snapshot-mysql:3306/snapshot
      # SEQ_DATABASE_URL: mysql://admin:pwd@snapshot-mysql:3306/snapshot

    ports:
      - "3000:3000"

networks:
  default:
    name: snapshot-network
